region: us-east-1 
debug: true
metrics:
  - aws_namespace: arpa-network-logs-test
    aws_metric_name: PartialSignatureGenerationTime
    aws_dimensions: [l1_chain_id, node_id]
    aws_dimension_select:
      node_id: ["0x1234567890123456789012345678901234567890"]
    aws_statistics: [Average]
    range_seconds: 86400
    period_seconds: 60
  - aws_namespace: arpa-network-logs-test
    aws_metric_name: TaskReceived
    aws_dimensions: [l1_chain_id, node_id]
    aws_dimension_select:
      node_id: ["0x1234567890123456789012345678901234567890"]
    aws_statistics: [Sum]
    range_seconds: 3600
    period_seconds: 60  
    nil_to_zero: true
  - aws_namespace: arpa-network-logs-test
    aws_metric_name: ListenerInterrupted
    aws_dimensions: [l1_chain_id, message, node_id]
    aws_dimension_select:
      node_id: ["0x1234567890123456789012345678901234567890"]
    aws_statistics: [Sum]
    range_seconds: 10800
    period_seconds: 60
    nil_to_zero: true