region: us-east-1 
delay_seconds: 0
metrics:
  - aws_namespace: arpa-network-logs-test
    aws_metric_name: PartialSignatureGenerationTime
    aws_dimensions: [l1_chain_id, node_id]
    aws_dimension_select:
      node_id: ["node_address_placeholder"]
    aws_statistics: [Average]
    range_seconds: 3600
    period_seconds: 60
  - aws_namespace: arpa-network-logs-test
    aws_metric_name: TaskReceived
    aws_dimensions: [l1_chain_id, node_id]
    aws_dimension_select:
      node_id: ["node_address_placeholder"]
    aws_statistics: [Sum]
    range_seconds: 3600
    period_seconds: 60  
    nil_to_zero: true
  - aws_namespace: arpa-network-logs-test
    aws_metric_name: ListenerInterrupted
    aws_dimensions: [l1_chain_id, message, node_id]
    aws_dimension_select:
      node_id: ["node_address_placeholder"]
    aws_statistics: [Sum]
    range_seconds: 3600
    period_seconds: 60