# string, <node account address you want to monitor>
node_address: "NODE_ACCOUNT_ADDRESS"

# integer or string, currently support '1' and '17000'
l1_chain_id: "L1_CHAIN_ID"

# string, <https rpc endpoint link>
provider_endpoint: "L1_RPC_ENDPOINT"

# integer, the interval of refreshing in seconds, like 30 means refresh per 30 seconds. We do not recommend changing this value.
interval: 30

# integer, you want this custom exporter to be communicating on which port. We do not recommend changing this value.
exporter_port: 8000