node_address: node_address_placeholder
l1_chain_id: l1_chain_id_placeholder
l1_rpc_endpoint: <YOUR_L1_RPC_ENDPOINT>


# eth mainnet example
# node_address: 0x1BD61FAAa74F7B2aAF414753B74d6070f821D16D
# chain_id: 1
# rpc_endpoint: https://ethereum-rpc.publicnode.com

# eth holesky example 
# node_address: 0x40E1b90DD56f85C2207980d3751eF71B74CA7f9C
# chain_id: 17000
# rpc_endpoint: https://ethereum-holesky-rpc.publicnode.com