version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  custom-exporter:
    build: 
      context: ./custom-exporter
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./custom-exporter/exporter.py:/app/exporter.py
      - ./custom-exporter/requirements.txt:/app/requirements.txt
      - ./custom-exporter/exporter-config.yml:/app/exporter-config.yml
    networks:
      - monitoring
  cloudwatch-exporter:
    image: prom/cloudwatch-exporter
    environment:
      - AWS_ACCESS_KEY_ID=<YOUR_AWS_ACCESS_KEY>
      - AWS_SECRET_ACCESS_KEY=<YOUR_AWS_SECRET_ACCESS_KEY>
    ports:
      - 9106:9106
    volumes:
      - ./aws_exporter_config.yml:/config/config.yml
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana:/etc/grafana/provisioning/datasources"
    networks:
      - monitoring