version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
  custom-exporter: {}

services:
  custom-exporter:
    image: custom-exporter:latest
    ports:
      - 8000:8000
    volumes:
      - ./custom-exporter/exporter-config.yml:/app/exporter-config.yml
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana:/etc/grafana/provisioning/datasources"
      - "./dashboards:/etc/grafana/provisioning/dashboards"
      - "./alerting:/etc/grafana/provisioning/alerting"
    networks:
      - monitoring