global:
  scrape_interval: 25s

scrape_configs:
  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']
  - job_name: 'custom-exporter'
    static_configs:
      - targets: ['custom-exporter:8000']