# string, <node address you want to monitor>
node_address: "node_address_placeholder"

# integer or string, currently support '1' and '17000'
chain_id: "l1_chain_id_placeholder"

# string, <https rpc endpoint link>
provider_endpoint: "<YOUR_L1_RPC_ENDPOINT>"

# integer, the interval of refreshing in seconds, like 10 means refresh per 10 seconds
interval: 10

# integer, you want this custom exporter to be communicating on which port
exporter_port: 8000