# string, <node account address you want to monitor>
node_address: "NODE_ACCOUNT_ADDRESS"

# integer or string, currently support '1' and '17000'
l1_chain_id: "L1_CHAIN_ID"

# string, <https rpc endpoint link>
provider_endpoint: "L1_RPC_ENDPOINT"

# integer, the interval of refreshing in seconds, like 10 means refresh per 10 seconds
interval: 10

# integer, you want this custom exporter to be communicating on which port
exporter_port: 8000