{
 "title": "ARPA Network Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Node Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_status{node_status=\"up\"} "
    }
   ]
  },
  {
   "title": "ETH Balance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "eth_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Address",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_address_info" }
   ]
  },
  { "title": "Group Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Group Index",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "group_index" }
   ]
  },
  {
   "title": "Group State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group_state{group_state=\"up\"} "
    }
   ]
  },
  {
   "title": "Group Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "group_size" }
   ]
  },
  { "title": "DKG Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "DKG Grouping  State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DKG_state{DKG_state=\"finished\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "last_over_time(committers{instance=\"custom-exporter:8000\", job=\"custom-exporter\"}[1m]) == 1"
    }
   ]
  },
  {
   "title": "Fetch Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fetch_times{instance=\"custom-exporter:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Randomness Task Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Partial Signature Generation Processing time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "aws_logs_error_count_average{class=\"None\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Randomness task count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "arpa_network_logs_test_task_received_average",
     "legendFormat": "{{request_id}}"
    }
   ]
  }
 ]
}